---
all:
  children:
    kvm_host:
      hosts:
        titan: {
          ansible_host: titan.dgnet
        }
    kube_workers:
      hosts:
        worker1: {
          ansible_host: worker1.dgnet
        }
        worker2: {
          ansible_host: worker2.dgnet
        }
        worker3: {
          ansible_host: worker3.dgnet
        }
  vars:
    ansible_connection: ssh 
    ansible_ssh_user: dgibson9503 
    ansible_ssh_pass: Jess!c@95M@d!son03
    ansible_become_password: Jess!c@95M@d!son03